name: Build CV PDF

on:
  push:
    paths:
      - '**.tex'
      - '**.md'
      - Makefile
  pull_request:
    paths:
      - '**.tex'
      - '**.md'
      - Makefile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv.tex
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: cv.pdf
